# Configuration Prometheus pour BantuOps Backend

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bantuops-monitor'
    environment: 'production'

# Configuration des règles d'alerte
rule_files:
  - "alert_rules.yml"

# Configuration des alertes
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Configuration des cibles de scraping
scrape_configs:
  # Métriques de l'application BantuOps
  - job_name: 'bantuops-backend'
    static_configs:
      - targets: ['bantuops-backend:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: bantuops-backend:8081

  # Métriques de la base de données PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Métriques de Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Métriques du système (Node Exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Métriques de Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Auto-monitoring de Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

# Configuration du stockage
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true